### ISSUE TITLE
Use of  semantic tags in html to improve  accessibility

### ISSUE THREAD

**Issue by Diem0n** [LyubomirT/remembered#10]
Instead of using `div` for inputs appropriate tags like `form` and `sections` would greatly improve accessibility

**Comment by LyubomirT** [comment]
Thanks for the idea!

As of now, I'd advise against using `<div>`s for several reasons, which include compatibility issues, customization limitations, pre-built styles, and events that need to be overwritten in order to make it work. Personally, I believe that it's better to leave as is, without changing anything. If you want, however, you can always create a different version of the repository with this changed, maybe it works out for you.
